import { Post, Sermon, Album, Activity, LiveStream, SiteSettings, CalendarEvent } from "@/types";

export const defaultSettings: SiteSettings = {
  churchName: "Trinity Baptist Church",
  tagline: "A Place of Grace, Faith & Community",
  serviceTimes: "Sundays at 9:00 AM & 11:00 AM",
  contactEmail: "trinitybaptistchurchilora@gmail.com",
  contactPhone: "+234 803 XXX XXXX",
  address: "Ilora, Oyo State, Nigeria",
  pastorName: "Rev'd Dr S. O. Mosebolatan",
  socialLinks: {
    facebook: "https://facebook.com/trinitybaptistilora",
    youtube: "https://youtube.com/@trinitybaptistilora",
  },
  gmailSenderEmail: "trinitybaptistchurchilora@gmail.com",
};

export const samplePosts: Omit<Post, "id">[] = [
  {
    title: "Walking in the Light of God's Word",
    body: "Dear beloved in Christ, as we begin this new week, let us remember that God's Word is a lamp unto our feet and a light unto our path. In Psalm 119:105, we are reminded that the scriptures guide us through every season of life. May you find strength, comfort, and direction as you meditate on His Word daily. The Lord bless you and keep you.",
    scripture: "Psalm 119:105",
    mediaType: "text",
    mediaUrl: "",
    amenCount: 47,
    pinned: true,
    status: "published",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    authorUid: "pastor1",
    authorName: "Rev'd Dr S. O. Mosebolatan",
  },
  {
    title: "Sunday Service Message: The Power of Faith",
    body: "Faith is the substance of things hoped for, the evidence of things not seen. In Hebrews 11:1, the Apostle Paul reminds us that faith is not merely wishful thinking—it is the confident assurance that God will fulfill His promises. Today, I encourage you to hold fast to your faith, even when the circumstances seem challenging. God is faithful, and He will never leave nor forsake you.",
    scripture: "Hebrews 11:1-6",
    mediaType: "video",
    mediaUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    youtubeId: "dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800",
    amenCount: 82,
    pinned: false,
    status: "published",
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    authorUid: "pastor1",
    authorName: "Rev'd Dr S. O. Mosebolatan",
  },
  {
    title: "Midweek Reflection: Grace Upon Grace",
    body: "For from His fullness we have all received, grace upon grace. John 1:16. What a wonderful truth to meditate upon this Wednesday! God's grace is not limited—it overflows abundantly in our lives. No matter what you faced this week, His grace is sufficient for you. Take a moment to thank Him for the countless graces He has bestowed upon you.",
    scripture: "John 1:16",
    mediaType: "text",
    mediaUrl: "",
    amenCount: 35,
    pinned: false,
    status: "published",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    authorUid: "pastor1",
    authorName: "Rev'd Dr S. O. Mosebolatan",
  },
  {
    title: "Special Announcement: Church Anniversary",
    body: "Praise the Lord! We are excited to announce that Trinity Baptist Church will be celebrating her anniversary next month. We invite all members, friends, and well-wishers to join us for a week-long celebration filled with praise, worship, thanksgiving, and fellowship. More details will be shared soon. God has been faithful to us as a church family!",
    scripture: "Psalm 107:1",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=800",
    thumbnailUrl: "https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=800",
    amenCount: 128,
    pinned: false,
    status: "published",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    authorUid: "pastor1",
    authorName: "Rev'd Dr S. O. Mosebolatan",
  },
];

export const sampleSermons: Omit<Sermon, "id">[] = [
  {
    title: "The Power of Faith",
    preacher: "Rev'd Dr S. O. Mosebolatan",
    date: "2026-06-21",
    scripture: "Hebrews 11:1-6",
    description: "An inspiring message about the transformative power of faith in the life of a believer. Learn how to strengthen your faith and trust God in every circumstance.",
    series: "Foundations of Faith",
    type: "video",
    youtubeId: "dQw4w9WgXcQ",
    featured: true,
  },
  {
    title: "Walking in Love",
    preacher: "Rev'd Dr S. O. Mosebolatan",
    date: "2026-06-14",
    scripture: "1 Corinthians 13:1-13",
    description: "A powerful teaching on agape love—how God loves us and how we are called to love one another unconditionally.",
    series: "Christian Virtues",
    type: "audio",
    audioUrl: "https://res.cloudinary.com/demo/video/upload/v1/sample_audio.mp3",
    durationSec: 2340,
    featured: false,
  },
  {
    title: "The Fruit of the Spirit",
    preacher: "Rev'd Dr S. O. Mosebolatan",
    date: "2026-06-07",
    scripture: "Galatians 5:22-23",
    description: "Discover the nine fruits of the Spirit and how they should manifest in the life of every Christian. A practical guide to spiritual growth.",
    type: "video",
    youtubeId: "dQw4w9WgXcQ",
    featured: false,
  },
  {
    title: "Overcoming Temptation",
    preacher: "Rev'd Dr S. O. Mosebolatan",
    date: "2026-05-31",
    scripture: "James 1:12-18",
    description: "Learn biblical strategies for overcoming temptation and living a victorious Christian life. God provides a way of escape in every temptation.",
    series: "Victorious Living",
    type: "audio",
    audioUrl: "https://res.cloudinary.com/demo/video/upload/v1/sample_audio.mp3",
    durationSec: 1980,
    featured: false,
  },
];

export const sampleAlbums: Omit<Album, "id">[] = [
  {
    title: "Sunday Service - June 22, 2026",
    eventDate: "2026-06-22",
    coverUrl: "https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=600",
    createdBy: "media1",
  },
  {
    title: "Youth Fellowship Night",
    eventDate: "2026-06-20",
    coverUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600",
    createdBy: "media1",
  },
  {
    title: "Baptism Ceremony - June 15",
    eventDate: "2026-06-15",
    coverUrl: "https://images.unsplash.com/photo-1507692049790-de58290a4334?w=600",
    createdBy: "media1",
  },
  {
    title: "Choir Ministration",
    eventDate: "2026-06-08",
    coverUrl: "https://images.unsplash.com/photo-1478147427282-58a87a120781?w=600",
    createdBy: "media1",
  },
];

export const sampleActivities: Omit<Activity, "id">[] = [
  {
    title: "Sunday Worship Service",
    weekday: 0,
    startTime: "09:00",
    endTime: "12:00",
    location: "Main Sanctuary",
    description: "Our main worship service with praise, prayer, and powerful preaching. All are welcome!",
    active: true,
  },
  {
    title: "Bible Study",
    weekday: 1,
    startTime: "17:00",
    endTime: "18:30",
    location: "Fellowship Hall",
    description: "In-depth study of God's Word. Come learn and grow in your understanding of Scripture.",
    active: true,
  },
  {
    title: "Prayer Meeting",
    weekday: 3,
    startTime: "17:00",
    endTime: "18:30",
    location: "Prayer Room",
    description: "A time of corporate prayer, intercession, and spiritual warfare. The prayer of a righteous person availeth much.",
    active: true,
  },
  {
    title: "Youth Fellowship",
    weekday: 5,
    startTime: "16:00",
    endTime: "18:00",
    location: "Youth Center",
    description: "Dynamic fellowship for young people—worship, games, discussions, and mentorship.",
    active: true,
  },
  {
    title: "Women's Fellowship",
    weekday: 2,
    startTime: "10:00",
    endTime: "12:00",
    location: "Fellowship Hall",
    description: "A gathering for women to encourage one another in faith, share experiences, and grow together.",
    active: true,
  },
];

export const sampleStreams: Omit<LiveStream, "id">[] = [
  {
    title: "Sunday Worship Service - Live",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    scheduledAt: new Date(Date.now() + 3 * 86400000).toISOString(),
    status: "scheduled",
    createdBy: "pastor1",
  },
];

export const sampleCalendarEvents: Omit<CalendarEvent, "id">[] = [
  {
    title: "Sunday Worship Service",
    date: "2026-06-29",
    startTime: "09:00",
    endTime: "12:00",
    location: "Main Sanctuary",
    description: "Weekly worship service",
    type: "service",
    createdBy: "pastor1",
  },
  {
    title: "Youth Fellowship Night",
    date: "2026-06-27",
    startTime: "16:00",
    endTime: "18:00",
    location: "Youth Center",
    description: "Youth fellowship and activities",
    type: "fellowship",
    createdBy: "pastor1",
  },
  {
    title: "Church Business Meeting",
    date: "2026-07-05",
    startTime: "14:00",
    endTime: "16:00",
    location: "Conference Room",
    description: "Monthly church business meeting",
    type: "meeting",
    createdBy: "pastor1",
  },
  {
    title: "Community Outreach",
    date: "2026-07-12",
    startTime: "09:00",
    endTime: "14:00",
    location: "Ilora Community",
    description: "Reaching out to the community with love and support",
    type: "special",
    createdBy: "pastor1",
  },
  {
    title: "Special Prayer & Fasting",
    date: "2026-07-18",
    startTime: "06:00",
    endTime: "18:00",
    location: "Church Premises",
    description: "Day of prayer and fasting for the church and nation",
    type: "special",
    createdBy: "pastor1",
  },
  {
    title: "Sunday Worship Service",
    date: "2026-07-06",
    startTime: "09:00",
    endTime: "12:00",
    location: "Main Sanctuary",
    description: "Weekly worship service",
    type: "service",
    createdBy: "pastor1",
  },
  {
    title: "Sunday Worship Service",
    date: "2026-07-13",
    startTime: "09:00",
    endTime: "12:00",
    location: "Main Sanctuary",
    description: "Weekly worship service",
    type: "service",
    createdBy: "pastor1",
  },
  {
    title: "Women's Conference",
    date: "2026-07-26",
    startTime: "10:00",
    endTime: "15:00",
    location: "Fellowship Hall",
    description: "Annual women's conference with special guest speakers",
    type: "special",
    createdBy: "pastor1",
  },
];
